steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/bq-to-ftp:$TAG_NAME', '.' , '-f', 'Dockerfile']
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bq-to-ftp:$TAG_NAME']
images:
  - 'gcr.io/$PROJECT_ID/bq-to-ftp:$TAG_NAME'