// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import io "io"
import mock "github.com/stretchr/testify/mock"

// IFTPService is an autogenerated mock type for the IFTPService type
type IFTPService struct {
	mock.Mock
}

// Send provides a mock function with given fields: name, src
func (_m *IFTPService) Send(name string, src io.Reader) error {
	ret := _m.Called(name, src)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, io.Reader) error); ok {
		r0 = rf(name, src)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
